# Generated by Django 4.1.13 on 2024-05-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_regiostermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegiosterModel',
        ),
    ]
