# Generated by Django 4.1.13 on 2024-05-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_commentsmodle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodle',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsmodel'),
        ),
    ]
